name: combat_goblin_prime
description: M1 Acquire storage implementation
version: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  path: ^1.9.0
  path_provider: ^2.1.2
  xml: ^6.5.0
